[project]
name = "llm-scratch"
version = "0.1.0"
description = "Building LLMs from Scratch (code based on the book)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.8.0",
]
